name: Wrangler Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install wrangler
        run: npm install -g wrangler
      - name: Build worker
        run: wrangler deploy --dry-run